name: javascript-client-payload-action
on: repository_dispatch
jobs:
  pass_client_payload_name:
    runs-on: ubuntu-latest
    name: pass_client_payload_name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ 
        with:
          client-payload: ${{ toJson(github.event.client_payload) }}"
